repos:

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        language: python
        entry: ruff check
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        types: [python]

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        language: python
        entry: ruff format
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy
        types: [python]
        args: ["."]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: uv run --locked pytest
        files: '(\.py$|\.sh$|\.md$|\.toml$|\.ya?ml$|\.json$|\.conf$|^uv\.lock$|^Makefile$|^detections_report/typst_assets/)'
        pass_filenames: false

  - repo: local
    hooks:
    -   id: uv-build
        name: uv-build
        entry: uv
        args: [build,--python,python3,--wheel]
        language: system
        files: '(\.py$|^pyproject\.toml$|^uv\.lock$|^detections_report/typst_assets/)'
        pass_filenames: false

  - repo: builtin
    hooks:
      - id: trailing-whitespace

      - id: end-of-file-fixer

      - id: check-json

      - id: check-yaml
        args: [--allow-multiple-documents]

      - id: check-added-large-files
