repos:

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        language: python
        entry: ruff check
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        types: [python]

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        language: python
        entry: ruff format
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        entry: uv run mypy
        types: [python]
        args: ["."]
        pass_filenames: false
        always_run: true

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       language: python
  #       entry: uv run pytest
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true

  # - repo: local
  #   hooks:
  #     - id: commitizen
  #       name: commitizen
  #       language: python
  #       entry: cz check --allow-abort --rev-range HEAD^..HEAD
  #       pass_filenames: false
  #       always_run: true

  - repo: local
    hooks:
    -   id: uv-build
        name: uv-build
        entry: uv
        args: [build,--wheel]
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: trailing-whitespace-fixer
        language: python
        types: [text]

      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: python
        types: [text]

      - id: check-json
        name: check-json
        entry: check-json
        language: python
        types: [json]

      - id: check-added-large-files
        name: check-added-large-files
        entry: check-added-large-files
        language: python
        types: [file]

      - id: debug-statements
        name: debug-statements
        entry: debug-statement-hook
        language: python
        types: [python]
