repos:

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.261'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        entry: black
        types: [python]
        additional_dependencies: [black==23.3.0]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        entry: mypy
        types: [python]
        args: [".", "--strict"]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        additional_dependencies: [pre-commit-hooks==4.0.1]

      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: python
        types: [text]
        additional_dependencies: [pre-commit-hooks==4.0.1]

      - id: check-json
        name: check-json
        entry: check-json
        language: python
        exclude: kafka-dump.json
        types: [json]
        additional_dependencies: [pre-commit-hooks==4.0.1]

      - id: check-added-large-files
        name: check-added-large-files
        entry: check-added-large-files
        exclude: kafka-dump.json
        language: python
        types: [file]
        additional_dependencies: [pre-commit-hooks==4.0.1]

      - id: debug-statements
        name: debug-statements
        entry: debug-statement-hook
        language: python
        types: [python]
        additional_dependencies: [pre-commit-hooks==4.0.1]
